name: Initiate Automated Deploy
description: Invokes a workflow to deploy the provided branch to a corresponding environment
inputs:
  branch:
    description: the branch to deploy
    required: true
  token:
    description: authentication token for communication with the GitHub API
    required: true
  workflow:
    description: name of the workflow file to run
    required: false
    default: deploy.yml
runs:
  using: 'node12'
  main: 'dist/index.js'